apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: 1.10.3
  components:
    ingressGateways:
    - enabled: true
      k8s:
        service:
          type: NodePort
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.ports
            value:
            - name: status-port
              nodePort: 30124
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 32000
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 32168
              port: 443
              protocol: TCP
              targetPort: 8443
      name: istio-ingressgateway
